name: Build and Deploy

on:
  push:
    branches: master

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    name: Deploy frontend

    steps:
    - uses: actions/checkout@v2.3.4

    - uses: actions/setup-node@v1
      name: Install node 12
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: |
        npm ci
      env:
        CI: true

    - name: Create build
      run: npm run build
      env:
        CI: true

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Deploy to S3
      run: aws s3 sync build/ s3://www.foreignlanguagereader.com

  deploy-storybook:
    runs-on: ubuntu-latest
    name: Deploy storybook

    steps:
    - uses: actions/checkout@v2.3.4

    - uses: actions/setup-node@v1
      name: Install node 12
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: |
        npm ci
      env:
        CI: true

    - name: Create build
      run: npm run build-storybook
      env:
        CI: true

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Deploy to S3
      run: aws s3 sync storybook-static/ s3://storybook.foreignlanguagereader.com
