name: Build and Deploy

on:
  push:
    branches: main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    name: Build frontend

    steps:
    - uses: actions/checkout@v2.3.4

    - uses: actions/setup-node@v2.1.5
      name: Install node 12
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: |
        npm ci --only=production
      env:
        CI: true

    - name: Create build
      run: npm run build
      env:
        CI: true
        DOMAIN_NAME: www.fluentlabs.io
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1.5.9
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    
    - name: Push to S3
      run: npm run deploy
      env:
        DOMAIN_NAME: www.fluentlabs.io # Probably doesn't do anything