name: Frontend Test

on:
  [pull_request]

jobs:
  build:
    name: Create test production build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - uses: actions/setup-node@v3.1.1
      name: Install node 14
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: npm ci --only=production
      env:
        CI: true

    - name: Create build
      run: npm run build
      env:
        CI: true
        DOMAIN_NAME: preprod.fluentlabs.io
    
    - uses: actions/upload-artifact@master
      name: Upload website content
      with:
        name: gatsby-public
        path: public

  test:
    name: Lint and test frontend
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - uses: actions/setup-node@v3.1.1
      name: Install node 14
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: |
        npm ci
      env:
        CI: true

    - name: Lint
      run: npm run lint-ci

    - name: Unit tests
      run: npm run test

    - name: End to end tests
      run: npm run test:e2e
  
  lighthouse-audit-local:
    name: Audit local build with lighthouse
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4

    - uses: actions/download-artifact@master
      name: Download website content
      with:
        name: gatsby-public
        path: public

    - name: Audit URLs using Lighthouse
      uses: treosh/lighthouse-ci-action@9.3.0
      with:
        configPath: './lighthouserc_local.json'
        uploadArtifacts: true # save results as an action artifacts
        temporaryPublicStorage: true # upload lighthouse report to the temporary storage
