name: Frontend Test

on:
  [pull_request]

jobs:
  build:
    name: Build and test frontend
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - uses: actions/setup-node@v2.1.5
      name: Install node 12
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: |
        npm ci
      env:
        CI: true

    - name: Validate security of dependencies
      run: npx audit-ci --high

    - name: Lint
      run: npm run lint-ci

    - name: Create build
      run: npm run build
      env:
        CI: true
    
    - uses: actions/upload-artifact@master
      name: Upload website content
      with:
        name: gatsby-public
        path: public
  
  deploy-foreign-language-reader:
    name: Deploy to preprod.foreignlanguagereader.com
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        name: Download website content
        with:
          name: gatsby-public
          path: public
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      
      - name: Push to S3
        run: aws s3 sync public/ s3://preprod.foreignlanguagereader.com --no-progress --delete

  deploy-fluentlabs:
    name: Deploy to preprod.fluentlabs.io
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        name: Download website content
        with:
          name: gatsby-public
          path: public
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      
      - name: Push to S3
        run: aws s3 sync public/ s3://preprod.fluentlabs.io --no-progress --delete