name: Frontend Test

on:
  [pull_request]

jobs:
  build:
    name: Build and test frontend
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - uses: actions/setup-node@v2.1.5
      name: Install node 12
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: |
        npm ci
      env:
        CI: true

    - name: Validate security of dependencies
      run: npx audit-ci --high

    - name: Lint
      run: npm run lint-ci

    - name: Create build
      run: npm run build
      env:
        CI: true
    
    - uses: actions/upload-artifact@master
      name: Upload website content
      with:
        name: gatsby-public
        path: public
  
  lighthouse-audit-local:
    name: Audit local build with lighthouse
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/download-artifact@master
        name: Download website content
        with:
          name: gatsby-public
          path: public

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v7
        env:
          # Needed because we didn't clone the repo
          LHCI_BUILD_CONTEXT__CURRENT_HASH: ${{ github.sha }}
        with:
          configPath: './lighthouserc_local.json'
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
  
  deploy-foreign-language-reader:
    name: Deploy to preprod.foreignlanguagereader.com
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/setup-node@v2.1.5
        name: Install node 12
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: |
          npm ci
        env:
          CI: true

      - uses: actions/download-artifact@master
        name: Download website content
        with:
          name: gatsby-public
          path: public
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      
      - name: Push to S3
        run: gatsby-plugin-s3 deploy --yes
        env:
          DOMAIN_NAME: preprod.foreignlanguagereader.com

  deploy-fluentlabs:
    name: Deploy to preprod.fluentlabs.io
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/setup-node@v2.1.5
        name: Install node 12
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: |
          npm ci
        env:
          CI: true

      - uses: actions/download-artifact@master
        name: Download website content
        with:
          name: gatsby-public
          path: public
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      
      - name: Push to S3
        run: gatsby-plugin-s3 deploy --yes
        env:
          DOMAIN_NAME: preprod.fluentlabs.io

  lighthouse-audit-fluentlabs:
    name: Audit Fluentlabs preprod with lighthouse
    needs: [deploy-fluentlabs]
    runs-on: ubuntu-latest
    steps:
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v7
        env:
          # Needed because we didn't clone the repo
          LHCI_BUILD_CONTEXT__CURRENT_HASH: ${{ github.sha }}
        with:
          urls: |
            https://preprod.fluentlabs.io/
          # budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage