name: Frontend Test

on:
  [pull_request]

jobs:
  build:
    name: Build and test frontend
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - uses: actions/setup-node@v1
      name: Install node 12
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: |
        npm ci
      env:
        CI: true

    - name: Validate security of dependencies
      run: npx audit-ci --moderate

    - name: Lint
      run: npm run lint

    - name: Create build
      run: npm run build
      env:
        CI: true

  storybook:
    name: Build and test storybook
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - uses: actions/setup-node@v1
      name: Install node 12
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: |
        npm ci
      env:
        CI: true

    - name: Build storybook
      run: npm run build-storybook
      env:
        CI: true
